apiVersion: v1
kind: Service
metadata:
  name: linear-algebra-pro-server
  labels:
    app: linear-algebra-pro-server
spec:
  type: ClusterIP
  # For external access, change to LoadBalancer:
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: linear-algebra-pro-server

